local config = require("lapis.config")
config("development", function()
  port(8080)
  gedis_port(5000)
  gedis_host('127.0.0.1')
  return github_secret('abdoabdo')
end)
return config("production", function()
  gedis_port(5000)
  gedis_host('127.0.0.1')
  port(6831)
  num_workers(4)
  return code_cache("on")
end)
